from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from app.core.dependencies import get_db, get_current_user, require_roles
from app.models.user_model import User
from app.models.incident_model import Incident
from app.models.report_model import IncidentReport
from app.schemas.report_schema import ReportResponse
from app.services.groq_service import generate_ai_incident_report

router = APIRouter(
    prefix="/reports",
    tags=["Reports"]
)


@router.post("/incidents/{incident_id}/generate", response_model=ReportResponse)
def generate_incident_report(
    incident_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(require_roles(["admin", "safety_officer"]))
):
    incident = db.query(Incident).filter(
        Incident.id == incident_id,
        Incident.user_id == current_user.id
    ).first()

    if not incident:
        raise HTTPException(
            status_code=404,
            detail="Incident not found"
        )

    existing_report = db.query(IncidentReport).filter(
        IncidentReport.incident_id == incident.id,
        IncidentReport.user_id == current_user.id
    ).first()

    if existing_report:
        return existing_report

    ai_text = generate_ai_incident_report(incident)

    ai_summary = ai_text
    risk_analysis = "Generated by Groq AI based on detected incident severity, type, and confidence score."
    recommended_action = "Review the AI-generated report and take appropriate safety action according to workplace policy."

    report = IncidentReport(
        incident_id=incident.id,
        user_id=current_user.id,
        ai_summary=ai_summary,
        risk_analysis=risk_analysis,
        recommended_action=recommended_action
    )

    db.add(report)
    db.commit()
    db.refresh(report)

    return report


@router.get("/incidents/{incident_id}", response_model=ReportResponse)
def get_incident_report(
    incident_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    report = db.query(IncidentReport).filter(
        IncidentReport.incident_id == incident_id,
        IncidentReport.user_id == current_user.id
    ).first()

    if not report:
        raise HTTPException(
            status_code=404,
            detail="Report not found. Generate report first."
        )

    return report